/// Flutter icons MyWhistleIcon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyWhistleIcon
///      fonts:
///       - asset: fonts/MyWhistleIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyWhistleIcon {
  MyWhistleIcon._();

  static const _kFontFam = 'MyWhistleIcon';

  static const IconData whistle = IconData(0xe800, fontFamily: _kFontFam);
}
